# Generated by Django 4.2.3 on 2023-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='variations',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images/product_images'),
        ),
        migrations.AddField(
            model_name='variations',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/product_images'),
        ),
        migrations.AddField(
            model_name='variations',
            name='img3',
            field=models.ImageField(blank=True, upload_to='images/product_images'),
        ),
        migrations.AddField(
            model_name='variations',
            name='img4',
            field=models.ImageField(blank=True, upload_to='images/product_images'),
        ),
        migrations.AddField(
            model_name='variations',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
