# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_variations_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
