# Generated by Django 4.2.3 on 2023-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_amount',
            field=models.FloatField(default=0),
        ),
    ]
